# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats seamlessly and silently with each pod install,
# but you can turn them off over here, if you wish.
#
# To learn more about CocoaPods analytics, see:
# https://guides.cocoapods.org/using/stats.html
#
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig not found. Try running ""flutter pub get"" in your project directory."
  end

  File.read(generated_xcode_build_settings_path).each_line do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
end

require_relative File.join('..', 'flutter', '.ios', 'podhelper')

flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        # For permission_handler
        'PERMISSION_CAMERA=1',
        'PERMISSION_MICROPHONE=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_BLUETOOTH=1',
        'PERMISSION_LOCATION=1'
      ]
    end
  end
end
